version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/node/Dockerfile
    volumes:
      - ./front:/usr/src/app:cached
    working_dir: /front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLLING=true